### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by priyank-p** [mnismt/checksum#1]
I just quickly glanced through this repo, when I saw checksum on electron app randomly:

* Going forward I think it would be better for this app have an about page. That pops up a modal or separate page.
* I think you should have a page that user can use to send feedback about your app. (Take a look at [send-feedback](https://github.com/electron-elements/send-feedback) to quickly do that! i do appreciate feedback on it)

Design: 
* I think you should put checksum logo on the bottom that's centered and rounded with shadow after the form.

**Comment by mnismt** [comment]
Thanks for your feedback, I will pay attention to your suggestions and add to the next update.

**Comment by priyank-p** [comment]
Closing, feel free to re-open.
